### ISSUE TITLE
Recently merged #3304 prevents clickable links everywhere

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-desktop#3305]
One commit before  #3304 was merged, clicking links was possible. 
Afterwards links are not clickable anymore (quoted or unquoted). 
Tested and reproducable in my from-source desktop install. 
Before providing a fixing PR please test it yourself (that quoted links don't work but links elsewhere work), thanks.

**Comment by achou11** [comment]
to potentially save some time, this change:

```css
.quoted-text, 
 .msg-body > .text { 
   a { 
     text-decoration: underline; 
     color: var(--messageTextLink); 
     pointer-events: none; 
   } 
 }
```

as you can see, this not only prevents pointer events on links within quoted text, but also links within normal message text (`.msg-body > .text`), causing the issue described.

this should instead be something like:

```css
.quoted-text, 
 .msg-body > .text { 
   a { 
     text-decoration: underline; 
     color: var(--messageTextLink); 
   } 
 }

.quoted-text {
  /* Prevent clicking links rendered in quoted text */
  a {
    pointer-events: none;
  }
}
```

(keep in mind that I've only looked at this code very briefly so there may be a something like this in place already)

the comment is optional but would highly recommend to make it clearer about why it's there, given that it's one of those small but impactful changes with lots of context.
